package org.miap.forms.reusablelovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_CUSTOMER {
	public static final String ID = "Customer";

	public static class L_CUSTOMER {
		public static final String ID = "Customer";
		public static final String I_ID = "id";
		public static final String I_ADDRESS_LINE_1 = "addressLine1";
		public static final String I_ADDRESS_LINE_2 = "addressLine2";
		public static final String I_NAME = "name";
		public static final String I_POST_CODE = "postCode";
		public static final String I_ADDRESS_LINE_3 = "addressLine3";
		public static final String I_TOWN = "town";

	}

}