package org.miap.forms.reusablelovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_VAT_RATES {
	public static final String ID = "VatRates";

	public static class L_VAT_RATES {
		public static final String ID = "VatRates";
		public static final String I_NOTES = "notes";
		public static final String I_RATE = "rate";
		public static final String I_NAME = "name";
		public static final String I_ID = "id";

	}

}