CREATE SCHEMA IF NOT EXISTS MIAP;
SET SCHEMA MIAP;

DROP SEQUENCE "MIAP"."PK_SEQUENCE";
CREATE SEQUENCE "MIAP"."PK_SEQUENCE";

DROP SEQUENCE "MIAP"."INV_POS_SEQUENCE";
CREATE SEQUENCE "MIAP"."INV_POS_SEQUENCE";

DROP TABLE IF EXISTS `CUSTOMER`;
CREATE  TABLE `CUSTOMER` (  
`ID` INT NOT NULL ,  `NAME` VARCHAR(100) NOT NULL , 
`ADDRESS_LINE1` VARCHAR(100) NOT NULL ,  
`ADDRESS_LINE2` VARCHAR(100) NULL ,  
`ADDRESS_LINE3` VARCHAR(100) NULL ,  
`POST_CODE` VARCHAR(20) NULL ,  
`TOWN` VARCHAR(100) NOT NULL ,  
PRIMARY KEY (`ID`) );

DROP TABLE IF EXISTS `CUSTOMER_CONTACT`;
CREATE  TABLE `CUSTOMER_CONTACT` (  
 `ID` INT NOT NULL ,  
 `CUST_ID` INT NOT NULL ,  
 `SALUT_ID` INT NULL , 
 `CONTACT_TYPE` INT NOT NULL , 
 `FIRST_NAME` VARCHAR(100) NULL ,  
 `LAST_NAME` VARCHAR(100) NOT NULL , 
 `PHONE` VARCHAR(30) NULL ,  
 `MOBILE` VARCHAR(30) NULL , 
 `EMAIL` VARCHAR(100) NULL , 
 PRIMARY KEY (`ID`) ,
FOREIGN KEY (`CUST_ID`) REFERENCES `miap`.`CUSTOMER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`SALUT_ID`) REFERENCES `miap`.`SALUTATIONS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`CONTACT_TYPE`) REFERENCES `miap`.`CONTACT_TYPES` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS `CUSTOMER_PROJECTS`;
CREATE  TABLE `CUSTOMER_PROJECTS` (  
 `ID` INT NOT NULL ,  
 `CUST_ID` INT NOT NULL ,  
 `NAME` VARCHAR(100) NOT NULL ,  
 `DESCRIPTION` VARCHAR(4000) NULL , 
 `PAY_RATE` DOUBLE NOT NULL ,  
 PRIMARY KEY (`ID`) ,
FOREIGN KEY (`CUST_ID`) REFERENCES `miap`.`CUSTOMER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS `INVOICE`;
CREATE  TABLE `INVOICE` (  
 `ID` INT NOT NULL ,  
 `INV_ID` INT NULL ,  
 `CUST_ID` INT NULL , 
 `COINF_ID` INT NOT NULL , 
 `PAYINF_ID` INT NOT NULL , 
 `NR` VARCHAR(100) NOT NULL , 
 `INV_DATE` DATE NOT NULL ,  
 `AMOUNT_EXCL_VAT` DOUBLE NULL , 
 `AMOUNT_INCL_VAT` DOUBLE NULL ,  
 `PRINTED` INT default '0' NOT NULL , 
 `PAID` INT default '0' NOT NULL , 
 PRIMARY KEY (`ID`) ,
FOREIGN KEY (`INV_ID`) REFERENCES `miap`.`INVOICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`CUST_ID`) REFERENCES `miap`.`CUSTOMER` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`COINF_ID`) REFERENCES `miap`.`COMPANY_INFORMATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`PAYINF_ID`) REFERENCES `miap`.`PAYMENT_INFORMATION` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
        
DROP TABLE IF EXISTS `INVOICE_POSITIONS`;
CREATE  TABLE `INVOICE_POSITIONS` (  
 `ID` INT NOT NULL ,  
 `INV_ID` INT NOT NULL ,  
 `VAT_ID` INT NULL , 
 `CUPR_ID` INT NOT NULL , 
 `POSITION` INT NOT NULL ,   
 `HOURS_WORKED` DOUBLE NOT NULL , 
 `DESCRIPTION` VARCHAR(4000) NOT NULL ,
 PRIMARY KEY (`ID`) ,
FOREIGN KEY (`INV_ID`) REFERENCES `miap`.`INVOICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`VAT_ID`) REFERENCES `miap`.`VAT_RATES` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
FOREIGN KEY (`CUPR_ID`) REFERENCES `miap`.`CUSTOMER_PROJECTS` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

DROP TABLE IF EXISTS `SALUTATIONS`;
CREATE  TABLE `SALUTATIONS` (  
`ID` INT NOT NULL , 
`VALUE` VARCHAR(20) NOT NULL ,   
PRIMARY KEY (`ID`) );

DROP TABLE IF EXISTS `VAT_RATES`;
CREATE  TABLE `VAT_RATES` ( 
 `ID` INT NOT NULL ,  
`RATE` DOUBLE NOT NULL ,  
`NAME` VARCHAR(50) NOT NULL ,  
`NOTES` VARCHAR(4000) NULL ,  
PRIMARY KEY (`ID`) );

DROP TABLE IF EXISTS `CONTACT_TYPES`;
CREATE  TABLE `CONTACT_TYPES` ( 
 `ID` INT NOT NULL ,   
`TYPE` VARCHAR(50) NOT NULL ,  
`DESCRIPTION` VARCHAR(4000) NULL ,  
PRIMARY KEY (`ID`) );

DROP TABLE IF EXISTS `COMPANY_INFORMATION`;
CREATE  TABLE `COMPANY_INFORMATION` (  
`ID` INT NOT NULL ,  
`NAME` VARCHAR(100) NOT NULL , 
`ADDRESS_LINE1` VARCHAR(100) NULL ,  
`ADDRESS_LINE2` VARCHAR(100) NULL ,  
`ADDRESS_LINE3` VARCHAR(100) NULL ,  
`POST_CODE` VARCHAR(20) NULL ,  
`TOWN` VARCHAR(100) NULL ,  
`BANK_NAME` VARCHAR(100) NOT NULL ,
`BANK_ADDRESS_LINE1` VARCHAR(100) NULL ,
`BANK_ADDRESS_LINE2` VARCHAR(100) NULL ,
`BANK_ADDRESS_LINE3` VARCHAR(100) NULL ,
`BANK_POST_CODE` VARCHAR(20) NULL ,
`BANK_TOWN` VARCHAR(100) NULL ,
`IBAN` VARCHAR(100) NOT NULL ,
PRIMARY KEY (`ID`) );

DROP TABLE IF EXISTS `PAYMENT_INFORMATION`;
CREATE  TABLE `PAYMENT_INFORMATION` ( 
 `ID` INT NOT NULL ,  
 `PAYMENT_TERMS` VARCHAR(200) NOT NULL ,
  PRIMARY KEY (`ID`) );
     



 