package org.entirej.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the EntireJProperties.  It
 * should not be modified by hand.
 */
public class EJ_PROPERTIES
{
    public static final String M_DEFAULT                   = "Default";
    public static final String M_EJ_MOBILE                 = "EJ_MOBILE";

    public static final String P_SB_SECTION_01             = "SB_SECTION_01";
    public static final String P_SB_SECTION_02             = "SB_SECTION_02";

    public static final String VA_VA_MOBILELIST_HEIGHLIGHT = "VA_MOBILELIST_HEIGHLIGHT";
    public static final String VA_VA_SB_SECTION_2          = "VA_SB_SECTION_2";

}