package org.miap.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MIAP005
{
    public static final String ID = "MIAP005";

    public static class B_PAYMENT_INFORMATION_BLOCK
    {
        public static final String ID              = "PaymentInformationBlock";
        public static final String I_ID            = "id";
        public static final String I_PAYMENT_TERMS = "paymentTerms";

    }

    public static class B_PAYMENT_INFORMATION_TOOLBAR
    {
        public static final String ID       = "PaymentInformationToolbar";
        public static final String I_CLOSE  = "close";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";

    }

    public static final String C_PAYMENT_INFORMATION_BLOCK   = "PaymentInformationBlock";
    public static final String C_PAYMENT_INFORMATION_TOOLBAR = "PaymentInformationToolbar";

    public static final String AC_TOOLBAR_CLOSE              = "TOOLBAR_CLOSE";
    public static final String AC_TOOLBAR_DELETE             = "TOOLBAR_DELETE";
    public static final String AC_TOOLBAR_EDIT               = "TOOLBAR_EDIT";
    public static final String AC_TOOLBAR_NEW                = "TOOLBAR_NEW";

}