package org.miap.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MIAP001
{
    public static final String ID = "MIAP001";

    public static class B_CUSTOMER_TOOLBAR
    {
        public static final String ID       = "CustomerToolbar";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";

    }

    public static class B_CUSTOMER_BLOCK
    {
        public static final String ID               = "CustomerBlock";
        public static final String I_ID             = "id";
        public static final String I_ADDRESS_LINE_1 = "addressLine1";
        public static final String I_ADDRESS_LINE_2 = "addressLine2";
        public static final String I_NAME           = "name";
        public static final String I_POST_CODE      = "postCode";
        public static final String I_ADDRESS_LINE_3 = "addressLine3";
        public static final String I_TOWN           = "town";
        public static final String I_SALUT_ID       = "salutId";
        public static final String I_SALUTATION     = "salutation";
        public static final String I_FIRST_NAME     = "firstName";
        public static final String I_LAST_NAME      = "lastName";
        public static final String I_PHONE          = "phone";
        public static final String I_MOBILE         = "mobile";
        public static final String I_EMAIL          = "email";

    }

    public static class B_CUSTOMER_CONTACT_TOOLBAR
    {
        public static final String ID       = "CustomerContactToolbar";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";

    }

    public static class B_CUSTOMER_CONTACT_BLOCK
    {
        public static final String ID                  = "CustomerContactBlock";
        public static final String I_FIRST_NAME        = "firstName";
        public static final String I_ID                = "id";
        public static final String I_LAST_NAME         = "lastName";
        public static final String I_PHONE             = "phone";
        public static final String I_EMAIL             = "email";
        public static final String I_MOBILE            = "mobile";
        public static final String I_CONTACT_TYPE      = "contactType";
        public static final String I_CUST_ID           = "custId";
        public static final String I_SALUT_ID          = "salutId";
        public static final String I_SALUTATION        = "salutation";
        public static final String I_CONTACT_TYPE_NAME = "contactTypeName";

    }

    public static class B_CUSTOMER_CONTACT_DETAILS_BLOCK
    {
        public static final String ID                  = "CustomerContactDetailsBlock";
        public static final String I_FIRST_NAME        = "firstName";
        public static final String I_ID                = "id";
        public static final String I_LAST_NAME         = "lastName";
        public static final String I_PHONE             = "phone";
        public static final String I_EMAIL             = "email";
        public static final String I_MOBILE            = "mobile";
        public static final String I_CONTACT_TYPE      = "contactType";
        public static final String I_CUST_ID           = "custId";
        public static final String I_SALUT_ID          = "salutId";
        public static final String I_SALUTATION        = "salutation";
        public static final String I_CONTACT_TYPE_NAME = "contactTypeName";

    }

    public static class B_CUSTOMER_PROJECTS_TOOLBAR
    {
        public static final String ID       = "CustomerProjectsToolbar";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";

    }

    public static class B_CUSTOMER_PROJECTS_BLOCK
    {
        public static final String ID            = "CustomerProjectsBlock";
        public static final String I_NAME        = "name";
        public static final String I_ID          = "id";
        public static final String I_PAY_RATE    = "payRate";
        public static final String I_CUST_ID     = "custId";
        public static final String I_DESCRIPTION = "description";

    }

    public static class L_SALUTATIONS
    {
        public static final String ID      = "Salutations";
        public static final String I_VALUE = "value";
        public static final String I_ID    = "id";

    }

    public static class L_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";

    }

    public static final String C_CUSTOMER_TOOLBAR     = "CustomerToolbar";
    public static final String C_CUSTOMER_BLOCK       = "CustomerBlock";
    public static final String C_CUSTOMER_DETAILS_TAB = "CustomerDetailsTab";

    public static class C_CUSTOMER_DETAILS_TAB_PAGES
    {
        public static final String CUSTOMER_CONTACTS = "CustomerContacts";
        public static final String CUSTOMER_PROJECTS = "CustomerProjects";

    }

    public static final String C_CUSTOMER_CONTACT_TOOLBAR       = "CustomerContactToolbar";
    public static final String C_CUSTOMER_CONTACTS_GROUP        = "CustomerContactsGroup";
    public static final String C_CUSTOMER_CONTACT               = "CustomerContact";
    public static final String C_CUSTOMER_CONTACT_DETAILS_BLOCK = "CustomerContactDetailsBlock";
    public static final String C_CUSTOMER_PROJECTS_TOOLBAR      = "CustomerProjectsToolbar";
    public static final String C_CUSTOMER_PROJECTS              = "CustomerProjects";

    public static final String AC_TOOLBAR_DELETE                = "TOOLBAR_DELETE";
    public static final String AC_TOOLBAR_EDIT                  = "TOOLBAR_EDIT";
    public static final String AC_TOOLBAR_NEW                   = "TOOLBAR_NEW";

}