package org.miap.forms.reusableblocks.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RB_STANDARD_TOOLBAR_QIUD
{
    public static final String ID = "StandardToolbarQIUD";

    public static class B_STANDARD_TOOLBAR_QIUD
    {
        public static final String ID       = "StandardToolbarQIUD";
        public static final String I_CLOSE  = "close";
        public static final String I_NEW    = "new";
        public static final String I_EDIT   = "edit";
        public static final String I_DELETE = "delete";

    }

    public static final String AC_TOOLBAR_CLOSE  = "TOOLBAR_CLOSE";
    public static final String AC_TOOLBAR_DELETE = "TOOLBAR_DELETE";
    public static final String AC_TOOLBAR_EDIT   = "TOOLBAR_EDIT";
    public static final String AC_TOOLBAR_NEW    = "TOOLBAR_NEW";

}