package org.entirej.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the EntireJProperties.  It
 * should not be modified by hand.
 */
public class EJ_PROPERTIES
{
    public static final String M_DEFAULT                           = "Default";

    public static final String P_SB_SECTION_1                      = "SB_SECTION_1";

    public static final String VA_VA_SINGLE_FORM_CONTAINER_TOOLBAR = "VA_SINGLE_FORM_CONTAINER_TOOLBAR";
    public static final String VA_VA_FORM_STANDARD_TOOLBAR         = "VA_FORM_STANDARD_TOOLBAR";
    public static final String VA_SB_SEC_01                        = "SB_SEC_01";

}