package org.miap.forms.reusablelovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_CONTACT_TYPES
{
    public static final String ID = "ContactTypes";

    public static class L_CONTACT_TYPES
    {
        public static final String ID            = "ContactTypes";
        public static final String I_TYPE        = "type";
        public static final String I_ID          = "id";
        public static final String I_DESCRIPTION = "description";

    }

}