package org.miap.forms.reusablelovdefs.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class RL_PAYMENT_INFORMATION
{
    public static final String ID = "PaymentInformation";

    public static class L_PAYMENT_INFORMATION
    {
        public static final String ID              = "PaymentInformation";
        public static final String I_ID            = "id";
        public static final String I_PAYMENT_TERMS = "paymentTerms";

    }

}