package org.miap.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MIAP006 {
	public static final String ID = "MIAP006";

	public static class B_SALUTATIONS_BLOCK {
		public static final String ID = "SalutationsBlock";
		public static final String I_VALUE = "value";
		public static final String I_ID = "id";

	}

	public static class B_SALUTATIONS_TOOLBAR {
		public static final String ID = "SalutationsToolbar";
		public static final String I_CLOSE = "close";
		public static final String I_NEW = "new";
		public static final String I_EDIT = "edit";
		public static final String I_DELETE = "delete";

	}

	public static final String C_SALUTATIONS_BLOCK = "SalutationsBlock";
	public static final String C_SALUTATIONS_TOOLBAR = "SalutationsToolbar";

	public static final String AC_TOOLBAR_CLOSE = "TOOLBAR_CLOSE";
	public static final String AC_TOOLBAR_DELETE = "TOOLBAR_DELETE";
	public static final String AC_TOOLBAR_EDIT = "TOOLBAR_EDIT";
	public static final String AC_TOOLBAR_NEW = "TOOLBAR_NEW";

}