package org.miap.forms.constants;

/* AUTO-GENERATED FILE.  DO NOT MODIFY. 
 *
 * This class was automatically generated by the
 * entirej plugin from the form.  It
 * should not be modified by hand.
 */
public class F_MIAP007M {
	public static final String ID = "MIAP007M";

	public static class B_VAT_RATES_TOOLBAR {
		public static final String ID = "VatRatesToolbar";
		public static final String I_CLOSE = "close";
		public static final String I_NEW = "new";
		public static final String I_EDIT = "edit";
		public static final String I_DELETE = "delete";

	}

	public static class B_VAT_RATES_BLOCK {
		public static final String ID = "VatRatesBlock";
		public static final String I_NOTES = "notes";
		public static final String I_RATE = "rate";
		public static final String I_NAME = "name";
		public static final String I_ID = "id";

	}

	public static final String C_VAT_RATES_TAB = "VatRatesTab";

	public static class C_VAT_RATES_TAB_PAGES {
		public static final String VAT_RATES_PAGE = "VatRatesPage";

	}

	public static final String C_VAT_RATES_BLOCK = "VatRatesBlock";
	public static final String C_VAT_RATES_TOOLBAR = "VatRatesToolbar";

	public static final String AC_TOOLBAR_CLOSE = "TOOLBAR_CLOSE";
	public static final String AC_TOOLBAR_DELETE = "TOOLBAR_DELETE";
	public static final String AC_TOOLBAR_EDIT = "TOOLBAR_EDIT";
	public static final String AC_TOOLBAR_NEW = "TOOLBAR_NEW";

}